# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bike.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 861)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(490, 730, 281, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSubmit = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.horizontalLayout_3.addWidget(self.pushButtonSubmit)
        self.pushButtonCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_3.addWidget(self.pushButtonCancel)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 780, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 740, 451, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 771, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 771, 50))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboCity = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboCity.setObjectName("comboCity")
        self.comboCity.addItem("")
        self.comboCity.addItem("")
        self.comboCity.addItem("")
        self.horizontalLayout.addWidget(self.comboCity)
        self.comboMonth = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboMonth.setObjectName("comboMonth")
        self.comboMonth.addItem("")
        self.comboMonth.addItem("")
        self.comboMonth.addItem("")
        self.comboMonth.addItem("")
        self.comboMonth.addItem("")
        self.comboMonth.addItem("")
        self.comboMonth.addItem("")
        self.horizontalLayout.addWidget(self.comboMonth)
        self.comboDay = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboDay.setObjectName("comboDay")
        self.comboDay.addItem("")
        self.comboDay.addItem("")
        self.comboDay.addItem("")
        self.comboDay.addItem("")
        self.comboDay.addItem("")
        self.comboDay.addItem("")
        self.comboDay.addItem("")
        self.comboDay.addItem("")
        self.horizontalLayout.addWidget(self.comboDay)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 110, 771, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(360, 20, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.webEngineView_1 = QtWebEngineWidgets.QWebEngineView(self.tab_1)
        self.webEngineView_1.setGeometry(QtCore.QRect(10, 10, 741, 541))
        self.webEngineView_1.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_1.setObjectName("webEngineView_1")
        self.webEngineView_1.raise_()
        self.label_5.raise_()
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.webEngineView_2 = QtWebEngineWidgets.QWebEngineView(self.tab_2)
        self.webEngineView_2.setGeometry(QtCore.QRect(10, 10, 741, 541))
        self.webEngineView_2.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_2.setObjectName("webEngineView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.webEngineView_3 = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.webEngineView_3.setGeometry(QtCore.QRect(10, 10, 741, 521))
        self.webEngineView_3.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_3.setObjectName("webEngineView_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_6.setGeometry(QtCore.QRect(320, 540, 111, 24))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_7.setGeometry(QtCore.QRect(430, 540, 91, 24))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 540, 111, 24))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_8.setGeometry(QtCore.QRect(120, 540, 101, 24))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_9.setGeometry(QtCore.QRect(220, 540, 91, 24))
        self.radioButton_9.setObjectName("radioButton_9")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 741, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_1 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_1.setGeometry(QtCore.QRect(10, 540, 81, 24))
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setAutoRepeat(False)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_2.setGeometry(QtCore.QRect(100, 540, 101, 24))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_3.setGeometry(QtCore.QRect(210, 540, 171, 24))
        self.radioButton_3.setObjectName("radioButton_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 741, 551))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonSubmit.setText(_translate("MainWindow", "Submit"))
        self.pushButtonCancel.setText(_translate("MainWindow", "Exit"))
        self.label_4.setText(_translate("MainWindow", "Developed by Jorge Rodriguez"))
        self.label.setText(_translate("MainWindow", "City"))
        self.label_2.setText(_translate("MainWindow", "Month"))
        self.label_3.setText(_translate("MainWindow", "Day"))
        self.comboCity.setItemText(0, _translate("MainWindow", "Chicago"))
        self.comboCity.setItemText(1, _translate("MainWindow", "New York"))
        self.comboCity.setItemText(2, _translate("MainWindow", "Washington"))
        self.comboMonth.setItemText(0, _translate("MainWindow", "all"))
        self.comboMonth.setItemText(1, _translate("MainWindow", "January"))
        self.comboMonth.setItemText(2, _translate("MainWindow", "February"))
        self.comboMonth.setItemText(3, _translate("MainWindow", "March"))
        self.comboMonth.setItemText(4, _translate("MainWindow", "April"))
        self.comboMonth.setItemText(5, _translate("MainWindow", "May"))
        self.comboMonth.setItemText(6, _translate("MainWindow", "June"))
        self.comboDay.setItemText(0, _translate("MainWindow", "all"))
        self.comboDay.setItemText(1, _translate("MainWindow", "Monday"))
        self.comboDay.setItemText(2, _translate("MainWindow", "Tuesday"))
        self.comboDay.setItemText(3, _translate("MainWindow", "Wednesday"))
        self.comboDay.setItemText(4, _translate("MainWindow", "Thursday"))
        self.comboDay.setItemText(5, _translate("MainWindow", "Friday"))
        self.comboDay.setItemText(6, _translate("MainWindow", "Saturday"))
        self.comboDay.setItemText(7, _translate("MainWindow", "Sunday"))
        self.label_5.setText(_translate("MainWindow", "Shortest Path Common Combination of Start-End Station"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Route"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Stations"))
        self.radioButton_6.setText(_translate("MainWindow", "Gender Map"))
        self.radioButton_7.setText(_translate("MainWindow", "Age Map"))
        self.radioButton_5.setText(_translate("MainWindow", "Trip Duration"))
        self.radioButton_8.setText(_translate("MainWindow", "Trip Count"))
        self.radioButton_9.setText(_translate("MainWindow", "User Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Maps"))
        self.radioButton_1.setText(_translate("MainWindow", "Gender"))
        self.radioButton_2.setText(_translate("MainWindow", "User Type"))
        self.radioButton_3.setText(_translate("MainWindow", "User Type and Gender"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Graphics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Statistics"))
from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
